language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
  - node_modules
before_script:
  - cd frontend
script:
  - npm install
  - npm run test
  - npm run build
deploy:
  provider: azure_web_apps
  site: "Vini-frontend"
  on:
    branch: master